# Generated by Django 3.0.3 on 2020-08-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInterface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='logo.png', upload_to='profile_pics'),
        ),
    ]
